### ISSUE TITLE
Array's

### ISSUE THREAD

**Issue by Binary-Labs-Code** [joghyrt/Blazor.JsonEditor#2]
When selecting an Array as the valuekind i need to be able to allow for array of objects, how would i do that?

**Comment by joghyrt** [comment]
@Binary-Labs-Code it is not supported right now. I am going to check how to make it.

**Comment by Binary-Labs-Code** [comment]
That would be great, thanks. ETA?

**Comment by joghyrt** [comment]
@Binary-Labs-Code sorry, no real ETA. Might be this week.

**Comment by Binary-Labs-Code** [comment]
That would be excellent.  Thankyou

**Comment by joghyrt** [comment]
@Binary-Labs-Code I have updates. Yesterday I spent some time with this issue. It is possible to do this but right now I have some doubts about how it should be edited and shown. But anyway I am going to add the possibility to customize it in custom views and editors. 

I am going to continue with these changes soon.

**Comment by Binary-Labs-Code** [comment]
Fantastic, If you can get it working, there is a fair few "coffees" in it for you. 

Thanks

**Comment by Binary-Labs-Code** [comment]
How are you doing with the potential changes?

**Comment by joghyrt** [comment]
Hello @Binary-Labs-Code it is in a process. Don’t have a lot of time for it now. I have changed some files already. Working on edit view and have some problems with it. I am going to continue with it on Friday/Weekend. 

Still no ETA.

**Comment by Binary-Labs-Code** [comment]
If you can work it out that would be great.  I could even pay for the work!

**Comment by joghyrt** [comment]
@Binary-Labs-Code, improvement is ready. Please check the demo. New functionality is available in 1.1.0, please update nuget package to the latest version.

If you use custom views you would need to adjust them.
