### ISSUE TITLE
Missing content javascript file in nuget package

### ISSUE THREAD

**Issue by johnmcbride** [joghyrt/Blazor.JsonEditor#3]
IT appears that the Blazor.JsonEditor.js is missing from the nuget package for a blazor server application. I've checked the nuget package and there is not a .js file in the package at all, even under the staticassets folder.

1. Create blazor server application (.net 7)
2. Following instructions on https://github.com/joghyrt/Blazor.JsonEditor/tree/main
3. Load site and check developer tools
4. See the error message about unable to load Blazor.JsonEditor.js

**Expected behavior**
Should load script

**Comment by joghyrt** [comment]
@johnmcbride thank you for the bug report! 

The issue was fixed in 1.0.7. Please update the Nuget package to the latest version.
