### ISSUE TITLE
Start with array instead of object

### ISSUE THREAD

**Issue by vankraster** [joghyrt/Blazor.JsonEditor#5]
I want to start Json Editor with an array [] instead of object {} .

I have binded the value to an empty array but it shows an object . 

   ```
  <JsonEditor @bind-Value="DemoJson.Json"
                 FieldName="@nameof(DemoJson.Json)"
                 ValidationFor="@(() => DemoJson.Json)"
                 CustomEditor="typeof(JsonItemCustomEditor)"
                 CustomItemView="typeof(JsonItemCustomView)"
                 CustomObjectView="typeof(JsonObjectCustomView)">
     </JsonEditor>
```

 
 ```
    public partial class CreateJson
   {
       private IndexModel DemoJson { get; set; } = new IndexModel();
 

       public CreateJson()
       {
           DemoJson.Json = "[]"; 
       }
 
   }
```

![image](https://github.com/joghyrt/Blazor.JsonEditor/assets/27769564/1d1265de-7093-4ca4-83b1-e452ec9e0222)

As you can see it starts with an object.
Can you please tell me if I am doing something wrong or if it is a bug ?

**Comment by joghyrt** [comment]
@vankraster Sorry but I think that jsonEditor could not be started as an array.
